### ISSUE TITLE
一些bug反馈及建议

### ISSUE THREAD

**Issue by springrain1** [eightHundreds/obsidian-kity-mind#1]
1、目前在插件的配置中，无法修改保存的路径，以及没法关闭按钮；
2、页面顶部占用了较多的空间，建议缩小一点点；
3、希望加入双链的支持，能够在思维导图中，直接跳转或打开对应的md文件。

**Comment by LeiYanhua** [comment]
感谢大佬！期待链接功能

**Comment by eightHundreds** [comment]
我不是很想去修改百度脑图的代码. 太难维护了.

双链加了
