### ISSUE TITLE
只能装一次？

### ISSUE THREAD

**Issue by chenxin0397** [eightHundreds/obsidian-kity-mind#13]
我刚才在沙盒里装了试用感觉不错，想在库里装就再也装不上了，沙盒里的删了重装也装不上了

**Comment by eightHundreds** [comment]
![4cef5faf1ef6b0f035a0104a22437c98](https://github.com/eightHundreds/obsidian-kity-mind/assets/18695431/aecaf1b8-d04a-424c-87c2-26dbce582086)

**Comment by chenxin0397** [comment]
![image](https://github.com/eightHundreds/obsidian-kity-mind/assets/73974352/92ba17f8-dae5-49c3-81d3-e6f828776214)

**Comment by eightHundreds** [comment]
我自己重装试了, 没问题.
我的步骤
1. 在插件管理删除 kity-mind 插件
2. 配置brat

<img width="731" alt="image" src="https://github.com/eightHundreds/obsidian-kity-mind/assets/18695431/59b6d23c-b13b-4585-b486-6dea94a16683">

3. 执行命令

<img width="441" alt="image" src="https://github.com/eightHundreds/obsidian-kity-mind/assets/18695431/3455f1d7-df90-4908-81ec-e7bb746209a3">
